-- SQL Schema for Smart Parking Lot Management System (Supabase PostgreSQL)

-- 1. Create custom Users table (extends auth.users)
CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    phone TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'user', -- 'admin' or 'user'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Disable RLS constraints for ease of development/testing (optional, but using standard public read/write policy is best for a quick demo)
CREATE POLICY "Public Read/Write Access for users" ON public.users 
    FOR ALL USING (true) WITH CHECK (true);

-- 2. Create Vehicles table
CREATE TABLE IF NOT EXISTS public.vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    vehicle_number TEXT NOT NULL UNIQUE,
    vehicle_type TEXT NOT NULL DEFAULT 'Car', -- 'Car', 'Bike', 'Truck'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read/Write Access for vehicles" ON public.vehicles 
    FOR ALL USING (true) WITH CHECK (true);

-- 3. Create Parking Slots table
CREATE TABLE IF NOT EXISTS public.parking_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_number TEXT NOT NULL UNIQUE,
    slot_type TEXT NOT NULL DEFAULT 'Four-Wheeler', -- 'Two-Wheeler', 'Four-Wheeler', 'Heavy-Vehicle'
    status TEXT NOT NULL DEFAULT 'available' -- 'available', 'occupied', 'booked'
);

ALTER TABLE public.parking_slots ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read/Write Access for parking_slots" ON public.parking_slots 
    FOR ALL USING (true) WITH CHECK (true);

-- Seed initial parking slots
INSERT INTO public.parking_slots (slot_number, slot_type, status) VALUES
('A101', 'Four-Wheeler', 'available'),
('A102', 'Four-Wheeler', 'available'),
('A103', 'Four-Wheeler', 'available'),
('A104', 'Four-Wheeler', 'available'),
('B101', 'Two-Wheeler', 'available'),
('B102', 'Two-Wheeler', 'available'),
('B103', 'Two-Wheeler', 'available'),
('C101', 'Heavy-Vehicle', 'available'),
('C102', 'Heavy-Vehicle', 'available')
ON CONFLICT (slot_number) DO NOTHING;

-- 4. Create Parking Records table
CREATE TABLE IF NOT EXISTS public.parking_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT NOT NULL REFERENCES public.vehicles(id) ON DELETE CASCADE,
    slot_id BIGINT REFERENCES public.parking_slots(id) ON DELETE SET NULL,
    entry_time TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    exit_time TIMESTAMP WITH TIME ZONE,
    total_hours NUMERIC(5,2),
    parking_fee NUMERIC(10,2),
    status TEXT NOT NULL DEFAULT 'active' -- 'active', 'completed', 'cancelled'
);

ALTER TABLE public.parking_records ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read/Write Access for parking_records" ON public.parking_records 
    FOR ALL USING (true) WITH CHECK (true);

-- 5. Create Waiting Queue table
CREATE TABLE IF NOT EXISTS public.waiting_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT NOT NULL UNIQUE REFERENCES public.vehicles(id) ON DELETE CASCADE,
    queue_position INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.waiting_queue ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read/Write Access for waiting_queue" ON public.waiting_queue 
    FOR ALL USING (true) WITH CHECK (true);
